disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping

excluded:
  - .build
  - DerivedData
  - Pods

identifier_name:
  min_length: 1
  excluded:
    - id
    - db
    - to

nesting:
  type_level: 2

cyclomatic_complexity:
  warning: 15
  error: 25
